### ISSUE TITLE
Use `common` configuration section more

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#142]
Currently, we don't use `common` section if `ferretdb` and `mongodb` sections are used:
https://github.com/FerretDB/dance/blob/edf7f8560a91eeadabf39b25b189c13aa392ce88/internal/config.go#L73-L75

We should allow `common.pass`, `common.skip` and `common.fail` to be non-empty. They should be merged into matching `ferretdb` and `mongodb` sections.

`common.default` and `common.stats` should remain empty if `ferretdb` or `mongodb` section is set (or both of them).

**Comment by noisersup** [comment]
Should I allow duplicates when merging? (In situations where the same test is placed both in common and ferretdb).
If not which behavior is expected?
- Panic
- Print a warning, do not merge duplicate and execute the code
- Do not print anything, do not merge duplicate and execute the code

**Comment by AlekSi** [comment]
Let's start with panic
