### ISSUE TITLE
Run MongoDB's jstests manually

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#165]
Let's run https://github.com/mongodb/mongo/tree/master/jstests against FerretDB manually. The goal is to understand how to do that, how tests setup and teardown work, what environment they require, etc. At least one "real" test should pass.

* #264
* https://github.com/FerretDB/FerretDB/pull/1611

**Comment by b1ron** [comment]
The legacy [shell](https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-debian11-5.0.14.tgz) is required to run their JavaScript tests. I am able to run all tests in `jstests/` using the legacy `mongo` shell.

[`resmoke.py`](https://github.com/mongodb/mongo/wiki/Test-The-Mongodb-Server#test-using-resmokepy) is responsible for setting up and tearing down jobs and running specific test suites. According to my testing the legacy shell is still a requirement for some resmoke tests.

```shell
admin@ip-172-31-7-87:~/mongo$ python buildscripts/resmoke.py run jstests/core/insert1.js --dbpathPrefix=data/db
[resmoke] 2022-11-29T11:58:14.982+0000 verbatim resmoke.py invocation: buildscripts/resmoke.py run jstests/core/insert1.js --dbpathPrefix=data/db
[resmoke] 2022-11-29T11:58:14.986+0000 YAML configuration of suite with_server
test_kind: js_test

selector:
  roots:
  - jstests/core/insert1.js

executor:
  config:
    shell_options:
      readMode: commands
  fixture:
    class: MongoDFixture
    mongod_options:
      set_parameters:
        enableTestCommands: 1

logging:
  executor:
    format: '[%(name)s] %(asctime)s %(message)s'
    handlers:
    - class: logging.StreamHandler
  fixture:
    format: '[%(name)s] %(message)s'
    handlers:
    - class: logging.StreamHandler
  tests:
    format: '[%(name)s] %(asctime)s %(message)s'
    handlers:
    - class: logging.StreamHandler
[executor] 2022-11-29T11:58:14.987+0000 Starting execution of js_tests...
[executor:js_test:job0] 2022-11-29T11:58:14.987+0000 Running job0_fixture_setup...
[js_test:job0_fixture_setup] 2022-11-29T11:58:14.987+0000 Starting the setup of MongoDFixture (Job #0).
[MongoDFixture:job0] Starting mongod on port 20000...
./mongod --setParameter enableTestCommands=1 --setParameter logComponentVerbosity={'replication': {'rollback': 2}, 'transaction': 4} --setParameter disableLogicalSessionCacheRefresh=true --setParameter transactionLifetimeLimitSeconds=86400 --setParameter maxIndexBuildDrainBatchSize=10 --dbpath=data/db/job0/resmoke --port=20000 --enableMajorityReadConcern=True
[MongoDFixture:job0] mongod started on port 20000 with pid 34962.
[js_test:job0_fixture_setup] 2022-11-29T11:58:14.994+0000 Waiting for MongoDFixture (Job #0) to be ready.
[MongoDFixture:job0] 2022-11-29T11:58:15.014+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
[MongoDFixture:job0] 2022-11-29T11:58:15.017+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
[MongoDFixture:job0] 2022-11-29T11:58:15.017+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=34962 port=20000 dbpath=data/db/job0/resmoke 64-bit host=ip-172-31-7-87
[MongoDFixture:job0] 2022-11-29T11:58:15.017+0000 I  CONTROL  [initandlisten] db version v4.2.8
[MongoDFixture:job0] 2022-11-29T11:58:15.017+0000 I  CONTROL  [initandlisten] git version: 43d25964249164d76d5e04dd6cf38f6111e21f5f
.
.
.
[MongoDFixture:job0] 2022-11-29T11:58:17.336+0000 I  CONTROL  [signalProcessingThread] now exiting
[MongoDFixture:job0] 2022-11-29T11:58:17.336+0000 I  CONTROL  [signalProcessingThread] shutting down with code:0
[MongoDFixture:job0] Successfully stopped the mongod on port 20000.
[js_test:job0_fixture_teardown] 2022-11-29T11:58:17.340+0000 Finished the teardown of MongoDFixture (Job #0).
[executor:js_test:job0] 2022-11-29T11:58:17.341+0000 job0_fixture_teardown ran in 0.14 seconds: no failures detected.
[executor] 2022-11-29T11:58:17.341+0000 Threads are completed!
[executor] 2022-11-29T11:58:17.341+0000 Summary: All 3 test(s) passed in 2.35 seconds.
[resmoke] 2022-11-29T11:58:17.341+0000 ================================================================================
[resmoke] 2022-11-29T11:58:17.341+0000 Summary of with_server suite: All 3 test(s) passed in 2.35 seconds.
3 test(s) ran in 2.35 seconds (3 succeeded, 0 were skipped, 0 failed, 0 errored)
    js_tests: All 3 test(s) passed in 2.35 seconds.
[resmoke] 2022-11-29T11:58:17.341+0000 Exiting with code: 0
```

**Comment by AlekSi** [comment]
How far we could go without using Python?

**Comment by b1ron** [comment]
I am not sure yet. Most of the suites rely on [these](https://github.com/mongodb/mongo/tree/master/buildscripts/resmokeconfig/suites) yaml files to setup the proper environment, however we could just run them manually as the PR states. I will figure this out.

**Comment by b1ron** [comment]
I made slightly more progress on this but it needs more investigation.

There are helper methods in the legacy shell pre-[5.1.0-rc0](https://jira.mongodb.org/issues/?jql=project+%3D+SERVER+AND+fixVersion+%3D+5.1.0-rc0) which forces the client to use OP_MSG for reads except for ismaster and some other commands. There is also a helper to force writes to do that same but it's not working.

```shell
// Force the shell to use OP_QUERY/OP_GET_MORE reads.
db.getMongo().forceReadMode('legacy');
 
// Force the shell to use find/getMore commands.
db.getMongo().forceReadMode('commands');

db.getMongo().forceWriteMode('commands'); // still sends OP_INSERT except for updates.
```

Wire protocol messages are not upgraded in the shell when requests are sent to FerretDB.

```javascript
// MongoDB shell version v5.0.14
> db.getMongo().forceWriteMode('commands');
> db.foo.insert({ 't': 'SHOULD_BE_OP_MSG' })
uncaught exception: Error: error doing query: failed: network error while attempting to run command 'getlasterror' on host '127.0.0.1:27017'  :
DB.prototype.runCommand@src/mongo/shell/db.js:188:19
executeGetLastError@src/mongo/shell/bulk_api.js:1047:20
executeBatchWithLegacyOps@src/mongo/shell/bulk_api.js:1065:30
Bulk/this.execute@src/mongo/shell/bulk_api.js:1184:21
DBCollection.prototype.insert@src/mongo/shell/collection.js:324:22
@(shell):1:1
.
.
.
Mongo Wire Protocol
    Message Length: 75
    Request ID: 0x00000014 (20)
    Response To: 0x00000000 (0)
    OpCode: Insert document (2002)
    Insert Flags
    fullCollectionName: test.foo
    Document
        Document length: 46
        Elements
            Element: _id
                Type: Object ID (0x07)
                ObjectID: 6387d87d849760a2378ba682
            Element: t
                Type: String (0x02)
                Length: 17
                Value: SHOULD_BE_OP_MSG
```

**Comment by b1ron** [comment]
I should of caught this earlier. [This](https://github.com/FerretDB/FerretDB/pull/1611) fails now because the [command](https://github.com/FerretDB/FerretDB/blob/main/internal/clientconn/conn.go#L395) is longer the first key and returns `"errmsg": "no such command: 'documents'"` etc. I will open a new issue that demonstrates it with a compat test.

**Comment by b1ron** [comment]
We are now able to run a small subset of the tests manually. Also, the tests themselves spawn new instances in the shell directly, so we can ignore resmoke.

I believe this task is done.

**Comment by AlekSi** [comment]
> the tests themselves spawn new instances inside the shell directly

Where?

I think we should avoid that if possible. Ideally, something external to jstests (be it our dance code or something else) should start an instance, run tests against it, and then stop it.

**Comment by b1ron** [comment]
> Where?

[Here](https://github.com/mongodb/mongo/blob/5bbadc66ed462aed3cc4f5635c5003da6171c25d/jstests/auth/auth-counters.js#L9) is an example. I am just adding it here for reference. 

As discussed on a call certain jstests will utilize [these runners](https://github.com/mongodb/mongo/wiki/Write-Tests-For-Server-Code#spawning-new-instances-inside-a-js-test). So, if we ran the [auth-counters.js](https://github.com/mongodb/mongo/blob/5bbadc66ed462aed3cc4f5635c5003da6171c25d/jstests/auth/auth-counters.js#L9) file for example it will inherently spawn a single node replica set as part of the entire test.

We should start by adding the [core tests](https://github.com/mongodb/mongo/tree/5bbadc66ed462aed3cc4f5635c5003da6171c25d/jstests/core) to the new runner in dance as they don't rely on the MongoDB shell runners (except in two files out of ~1066 I think).

**Comment by AlekSi** [comment]
See #276 and FerretDB/FerretDB#1645.
