### ISSUE TITLE
Run "service-tests" manually

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#166]
Let's run https://github.com/mongodb-developer/service-tests against FerretDB manually. The goal is to understand how to do that, how tests setup and teardown work, what environment they require, etc. At least one "real" test should pass.

**Comment by b1ron** [comment]
Due to https://github.com/mongodb-developer/service-tests/pull/17 we can run these and at least have somewhat accurate results. I will provide a breakdown table similar to [this](https://github.com/mongodb-developer/service-tests#results-breakdown-from-periodic-test-runs) once completed.

**Comment by AlekSi** [comment]
@b1ron I guess this is done?

**Comment by b1ron** [comment]
> @b1ron I guess this is done?

Yes it is.
