### ISSUE TITLE
Run service-tests with dance

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#318]
https://github.com/mongodb-developer/service-tests

We don't want to use their Python code, but we could make a new dance runner that would use their test suites like https://github.com/mongodb-developer/service-tests/blob/master/post-5.0/test-suites/6.0/dbaas_core.yml

**Comment by b1ron** [comment]
FYI they've re-organized the core directory, see https://jira.mongodb.org/browse/SERVER-64473.
