### ISSUE TITLE
Investigate all dbaas_core failures

### ISSUE THREAD

**Issue by b1ron** [FerretDB/dance#424]
This will take considerable time as each failure will need an issue and a PR with a repro. There are currently only 351 failures but this is due https://pkg.go.dev/path/filepath#Glob not supporting globstar, i.e. match all files and zero or more directories and subdirectories.

As a side note globstar can be enabled in Bash 4 by doing `shopt -s globstar` but I am not sure if his will allow Go to utilize the shell option.

The dbaas_core suite has ~1k files in total, I think.

**Comment by AlekSi** [comment]
> but I am not sure if his will allow Go to utilize the shell option.

Nope.

Why do we need globstar?

**Comment by b1ron** [comment]
> Why do we need globstar?

To not have to manually provide all files in all directories that end with `.js`. I suppose we can do this manually.

**Comment by AlekSi** [comment]
But we don't need to provide all _files_, only directories, and there are not so many of them

**Comment by b1ron** [comment]
> But we don't need to provide all files, only directories, and there are not so many of them

And _all_ the directories inside those directories. But I believe there are not too many. I will be adding them all in any event.

**Comment by AlekSi** [comment]
I think we should do to close that issue:
* Split `dbaas_core.yml` into multiple configurations to make them run in parallel.
* Investigate if we could run multiple files per `docker compose run` invocation.

**Comment by b1ron** [comment]
> Investigate if we could run multiple files per docker compose run invocation.

Perhaps we could use a `.mongoshrc` file with predefined `TestData` for each test before `docker compose run` is executed. I will need to see if that could work.
