### ISSUE TITLE
Run go-ycsb

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/dance#425]
https://github.com/pingcap/go-ycsb

Do the most basic simplest fastest integration into the dance tool (including a new runner) and CI. We will tweak and change everything later, but we need to start somewhere.

**Comment by b1ron** [comment]
This sounds great!

**Comment by b1ron** [comment]
@AlekSi I am going to add https://github.com/pingcap/go-ycsb as a submodule and then build the binary from source. We also need access to the [worloads](https://github.com/pingcap/go-ycsb/tree/master/workloads) directory.

I cannot seem to add it as a tool dependency. Maybe you could help me with figuring that out at a later stage. They use a [Makefile](https://github.com/pingcap/go-ycsb/blob/master/Makefile).

```
github.com/FerretDB/dance/tools imports
        github.com/pingcap/go-ycsb: module github.com/pingcap/go-ycsb@latest found (v1.0.1), but does not contain package github.com/pingcap/go-ycsb
```

**Comment by b1ron** [comment]
I chose to add a new Dockerfile instead.

**Comment by AlekSi** [comment]
@b1ron just assume for now that the binary exists in $PATH
