### ISSUE TITLE
Do exponential backoff to handle transient errors

### ISSUE THREAD

**Issue by b1ron** [FerretDB/dance#582]
Some tests, particularly `dbaas_core` are quite problematic as they generate significant load which cause unexpected failures, when they should, in fact pass. https://github.com/FerretDB/dance/pull/562 has greatly reduced the number of unexpected results but some, still fail. 

No more than 1 to 3 tests fail unexpectedly AFAIK.

I think the shell has build-in retry logic but that does not seem to be enough. We should probably use the [ctxutil](https://github.com/FerretDB/FerretDB/blob/main/internal/util/ctxutil/ctxutil.go) package. If possible, we should avoid retrying expected failures as it will slow things down.

Some example errors seen on CI: [Connection refused](https://github.com/FerretDB/dance/actions/runs/6120875853/job/16613570456?pr=570#step:7:272), and [collection/table does not exist](https://github.com/FerretDB/dance/actions/runs/6120875853/job/16613570456?pr=570#step:7:296).

**Comment by AlekSi** [comment]
I don't think we should do that
